### ISSUE TITLE
Players crashing on server with this mod installed

### ISSUE THREAD

**Issue by backgroundman** [MineLittlePony/Mson#4]
Only players with this mod are crashing on my server, and they crash at night time. here are the crash logs from two of the players
[crash-2020-05-23_23.02.51-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/4770898/crash-2020-05-23_23.02.51-client.txt)
[crash-2020-06-07_07.58.34-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/4770903/crash-2020-06-07_07.58.34-client.txt)

**Comment by Sollace** [comment]
This should be fixed now in MineLittlePony 4.0.10
